name: "Test"
on:
  pull_request:
  push:
jobs:
  tests-macos:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v3
    - run: brew install rebar3
    - run: make ci
    - uses: actions/upload-artifact@v2
      if: always()
      with:
        name: ct-logs
        path: _build/test/logs
        retention-days: 5
  tests-linux:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: cachix/install-nix-action@v22
      with:
        nix_path: nixpkgs=channel:nixos-unstable
    - run: nix-shell --run 'make ci'
    - uses: actions/upload-artifact@v2
      if: always()
      with:
        name: ct-logs
        path: _build/test/logs
        retention-days: 5
  docker_smoke_tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - run: make docker-smoke-tests
