name: "Test"
on:
  pull_request:
  push:
jobs:
  tests:
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v2.3.4
    - uses: cachix/install-nix-action@v16
      with:
        nix_path: nixpkgs=channel:nixos-unstable
    - run: nix-shell --run 'make ci'
    - uses: actions/upload-artifact@v2
      if: always()
      with:
        name: ct-logs
        path: _build/test/logs
        retention-days: 5
  docker_smoke_tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2.3.4
    - run: make docker-smoke-tests
